const dummyLoans = [
  {
    clientId: "CL001",
    loanId: "LN2000",
    fileName: "TMLBC098",
    dob: "1990-01-15",
    phone: "+2348012345670",
    email: "client1@example.com",
    address: "1 Example Street, Lagos",
    businessName: "Business One",
    date: "2025-05-01",
    loanDetails: "New Loan",
    ownershipType: "Sole Proprietorship",
    otherInfo: "First time applicant",
    employerId: "EMP3000",
    createdBy: "Admin",
    numberOfStaffs: "5",
    businessStartupDate: "2015-01-10",
    status: "Active",
    loanAmount: "NA",
    forms: {
      statementOfAccount: "statement1.pdf",
      idCard: "id1.jpg",
      passport: "passport1.jpg",
      loanInvoice: "invoice1.pdf",
      physicalFormUpload: "form1.pdf",
    },
    guarantors: [
      {
        name: "John Doe",
        occupation: "Engineer",
        phone: "+2348100000001",
        email: "guarantor1@example.com",
        address: "Lagos Mainland",
        relationship: "Friend",
        forms: {
          idCard: "g1_id1.jpg",
          passport: "g1_pass1.jpg",
          formUpload: "g1_form1.pdf",
        },
      },
      {
        name: "Jane Smith",
        occupation: "Teacher",
        phone: "+2347000000001",
        email: "guarantor2@example.com",
        address: "Ikeja, Lagos",
        relationship: "Colleague",
        forms: {
          idCard: "g2_id1.jpg",
          passport: "g2_pass1.jpg",
          formUpload: "g2_form1.pdf",
        },
      },
    ],
    name: "Tunde Olawale",
    purpose: "Asset Financing",
    totalCostofAsset: 5000000,
    asset: "Generator",
    assetdescription: "Heavy-duty industrial generator",
    assetQuantity: 2,
    assetPrice: 2500000,
    Supplier: "Energy Supplies Ltd.",
    equityContribution: 500000,
    additionalClientContribution: 0,
    supplierQuote: 4800000,
    costOfAssetFinancedByTasuwab: 4400000,
    InstallmentPeriod: 12,
    AverageInflationRate: 10,
    InflationMultiplier: 1.1,
    postInflationCost: 5280000,
    MarketRiskPremium: 5,
    operationalExpenses: 3,
    totalRealOperationalCost: 5580000,
    requiredProfitMargin: 15,
    minimumAssetPrice: 6000000,
    profitEstimate: 1000000,
    profitPercent: 18,

    repayment: [
      {
        loanID: "LN2000",
        DocNbr: "TRXN001",
        RepaymentDate: new Date().toISOString().slice(0, 10),
        date: new Date().toISOString().slice(0, 10),
        Repaidamount: (6000000 / 12) * 10,
        amountRemaining: 6000000 - 5000000,
        MonthsRemaining: 2,
        CreatedBy: "Admin",
      },
    ],
  },
  {
    clientId: "CLT1001",
    loanId: "LN2001",
    fileName: "TMLBC099",
    dob: "1989-02-20",
    phone: "+2348023456781",
    email: "client2@example.com",
    address: "2 Broad Street, Abuja",
    businessName: "Business Two",
    date: "2025-05-02",
    status: "Pending",
    loanDetails: "New Loan",
    ownershipType: "Partnership",
    otherInfo: "Existing client",
    employerId: "EMP3001",
    numberOfStaffs: "7",
    businessStartupDate: "2014-06-12",
    loanAmount: "NA",
    forms: {
      statementOfAccount: "statement2.pdf",
      idCard: "id2.jpg",
      passport: "passport2.jpg",
      loanInvoice: "invoice2.pdf",
      physicalFormUpload: "form2.pdf",
    },
    guarantors: [
      {
        name: "Ayo Balogun",
        occupation: "Trader",
        phone: "+2348100000002",
        email: "guarantor3@example.com",
        address: "Abuja Central",
        relationship: "Cousin",
        forms: {
          idCard: "g1_id2.jpg",
          passport: "g1_pass2.jpg",
          formUpload: "g1_form2.pdf",
        },
      },
      {
        name: "Fatima Musa",
        occupation: "Accountant",
        phone: "+2347000000002",
        email: "guarantor4@example.com",
        address: "Maitama, Abuja",
        relationship: "Sister",
        forms: {
          idCard: "g2_id2.jpg",
          passport: "g2_pass2.jpg",
          formUpload: "g2_form2.pdf",
        },
      },
    ],
    name: "Client Two",
    createdBy: "Admin",

    purpose: "Asset Financing",
    totalCostofAsset: "500000",
    asset: "Generator",
    assetdescription: "Heavy-duty industrial generator",
    assetQuantity: "1",
    assetPrice: "500000",
    Supplier: "RetailTech Ltd.",
    equityContribution: 100000,
    additionalClientContribution: 0,
    supplierQuote: 400000,
    costOfAssetFinancedByTasuwab: 400000,
    InstallmentPeriod: 12,
    AverageInflationRate: 2,
    InflationMultiplier: 1.27,
    postInflationCost: 507297,
    MarketRiskPremium: 1,
    operationalExpenses: 5,
    totalRealOperationalCost: 537735,
    requiredProfitMargin: 5,
    minimumAssetPrice: 566037,
    profitEstimate: 166037,
    profitPercent: 41.51,
  },
];
export default dummyLoans;
