const dummyLoans = [
  {
    LoanID: "1",
    Equity: 20,
    clientId: "CL001",
    bank: "GTBank",
    bankAccount: "0123456789",
    loanAmount: 250000,
    loanType: "Personal",
    interestRate: 12,
    loanPurpose: "Business Expansion",
    guarantors: [
      {
        name: "John Doe",
        email: "john@example.com",
        phone: "08012345678",
        address: "12 Marina Street, Lagos",
      },
      {
        name: "Jane Smith",
        email: "jane@example.com",
        phone: "08123456789",
        address: "20 Allen Avenue, Ikeja",
      },
    ],
    document: "loan_doc_001.pdf",
    memo: "Urgent disbursement needed.",
    status: "Pending",
    currentBalance: 45000,
    unpostedInterestBalance: 1500,
    transactions: [
      {
        date: "2025-01-15",
        type: "Disbursement",
        amount: 50000,
        description: "Initial loan disbursement",
        status: "Approved",
        docNbr: "DOC-1-1",
        interestRate: 12,
      },
      {
        date: "2025-02-15",
        type: "Repayment",
        amount: 5000,
        description: "First repayment",
        status: "Pending",
        docNbr: "DOC-1-2",
        interestRate: 12,
      },
      {
        date: "2025-03-15",
        type: "Repayment",
        amount: 5000,
        description: "Second repayment",
        status: "Rejected",
        docNbr: "DOC-1-3",
        interestRate: 12,
      },
    ],
  },
  {
    LoanID: "2",
    Equity: 20,
    clientId: "CL002",
    bank: "Access Bank",
    bankAccount: "0987654321",
    loanAmount: 500000,
    loanType: "Mortgage",
    interestRate: 10,
    loanPurpose: "Home Purchase",
    guarantors: [
      {
        name: "Mark Anthony",
        email: "marka@example.com",
        phone: "08033445566",
        address: "15 Bourdillon Road, Ikoyi",
      },
    ],
    document: "loan_doc_002.pdf",
    memo: "Client needs approval by end of week.",
    status: "Approved",
    currentBalance: 200000,
    unpostedInterestBalance: 8000,
    transactions: [
      {
        date: "2025-01-20",
        type: "Disbursement",
        amount: 200000,
        description: "Initial mortgage disbursement",
        status: "Approved",
        docNbr: "DOC-2-1",
        interestRate: 10,
      },
      {
        date: "2025-02-20",
        type: "Repayment",
        amount: 20000,
        description: "Monthly repayment",
        status: "Pending",
        docNbr: "DOC-2-2",
        interestRate: 10,
      },
    ],
  },
  {
    LoanID: "3",
    Equity: 20,
    clientId: "CL003",
    bank: "UBA",
    bankAccount: "1234567890",
    loanAmount: 150000,
    loanType: "Car Loan",
    interestRate: 9,
    loanPurpose: "Purchase of Used Car",
    guarantors: [
      {
        name: "Angela Nwosu",
        email: "angela@example.com",
        phone: "07099887766",
        address: "22 Ogudu Road, Lagos",
      },
    ],
    document: "loan_doc_003.pdf",
    memo: "Client requested a flexible repayment plan.",
    status: "Rejected",
    currentBalance: 75000,
    unpostedInterestBalance: 3000,
    transactions: [
      {
        date: "2025-01-10",
        type: "Application Fee",
        amount: 10000,
        description: "Fee for car loan application",
        status: "Rejected",
        docNbr: "DOC-3-1",
        interestRate: 9,
      },
    ],
  },
  {
    LoanID: "4",
    Equity: 20,
    clientId: "CL004",
    bank: "Zenith Bank",
    bankAccount: "5678901234",
    loanAmount: 800000,
    loanType: "Business Loan",
    interestRate: 15,
    loanPurpose: "Retail Store Expansion",
    guarantors: [
      {
        name: "Emeka Obi",
        email: "emeka@example.com",
        phone: "08055667788",
        address: "5 Broad Street, Lagos",
      },
      {
        name: "Chidinma Okafor",
        email: "chidimma@example.com",
        phone: "08022335566",
        address: "8 Ikorodu Road, Lagos",
      },
    ],
    document: "loan_doc_004.pdf",
    memo: "Needs disbursement before end of Q3.",
    status: "Pending",
    currentBalance: 100000,
    unpostedInterestBalance: 5000,
    transactions: [
      {
        date: "2025-01-25",
        type: "Disbursement",
        amount: 100000,
        description: "Initial business loan disbursement",
        status: "Approved",
        docNbr: "DOC-4-1",
        interestRate: 15,
      },
      {
        date: "2025-02-25",
        type: "Repayment",
        amount: 15000,
        description: "Repayment for January",
        status: "Pending",
        docNbr: "DOC-4-2",
        interestRate: 15,
      },
    ],
  },
  {
    LoanID: "5",
    Equity: 20,
    clientId: "CL005",
    bank: "First Bank",
    bankAccount: "3456789012",
    loanAmount: 300000,
    loanType: "Education Loan",
    interestRate: 8,
    loanPurpose: "Tuition Fees",
    guarantors: [
      {
        name: "Aisha Bello",
        email: "aisha@example.com",
        phone: "08145566778",
        address: "19 Zaria Crescent, Abuja",
      },
    ],
    document: "loan_doc_005.pdf",
    memo: "For child’s school fees, urgent attention needed.",
    status: "Approved",
    currentBalance: 100000,
    unpostedInterestBalance: 4000,
    transactions: [
      {
        date: "2025-01-30",
        type: "Disbursement",
        amount: 100000,
        description: "Initial education loan disbursement",
        status: "Approved",
        docNbr: "DOC-5-1",
        interestRate: 8,
      },
      {
        date: "2025-02-28",
        type: "Repayment",
        amount: 15000,
        description: "Monthly repayment",
        status: "Pending",
        docNbr: "DOC-5-2",
        interestRate: 8,
      },
    ],
  },
  {
    LoanID: "6",
    Equity: 20,
    clientId: "CL006",
    bank: "Stanbic IBTC",
    bankAccount: "6789012345",
    loanAmount: 600000,
    loanType: "Agricultural Loan",
    interestRate: 11,
    loanPurpose: "Purchase of farming equipment",
    guarantors: [
      {
        name: "Usman Garba",
        email: "usman@example.com",
        phone: "07012349876",
        address: "10 Kano Road, Kaduna",
      },
    ],
    document: "loan_doc_006.pdf",
    memo: "Monitoring of equipment usage recommended.",
    status: "Pending",
    currentBalance: 250000,
    unpostedInterestBalance: 10000,
    transactions: [
      {
        date: "2025-01-12",
        type: "Disbursement",
        amount: 250000,
        description: "First disbursement for equipment purchase",
        status: "Approved",
        docNbr: "DOC-6-1",
        interestRate: 11,
      },
      {
        date: "2025-03-12",
        type: "Repayment",
        amount: 20000,
        description: "Repayment for February",
        status: "Pending",
        docNbr: "DOC-6-2",
        interestRate: 11,
      },
      {
        date: "2025-04-12",
        type: "Repayment",
        amount: 20000,
        description: "Repayment for March",
        status: "Pending",
        docNbr: "DOC-6-3",
        interestRate: 11,
      },
    ],
  },
];

export default dummyLoans;
