const dummyClients = [
  {
    clientId: "CL001",
    accountnumber: "ACC001",
    email: "client1@example.com",
    firstName: "Tunde",
    lastName: "Olawale",
    phone: "08098765432",
    dob: "1990-05-14",
    gender: "Male",
    maritalStatus: "Single",
    address: "45 Allen Avenue",
    town: "Ikeja",
    state: "Lagos",
    nationality: "Nigerian",
    occupation: "Software Engineer",
    employer: "Andela",
    employerAddress: "20, Herbert Macaulay Way, Yaba, Lagos",
  },
  {
    clientId: "CL002",
    accountnumber: "ACC002",

    email: "client2@example.com",
    firstName: "Chioma",
    lastName: "Okonkwo",
    phone: "08112233445",
    dob: "1985-08-22",
    gender: "Female",
    maritalStatus: "Married",
    address: "7 Admiralty Way",
    town: "Lekki",
    state: "Lagos",
    nationality: "Nigerian",
    occupation: "Banker",
    employer: "UBA",
    employerAddress: "UBA House, Marina, Lagos",
  },
  {
    clientId: "CL003",
    accountnumber: "ACC003",

    email: "client3@example.com",
    firstName: "Ahmed",
    lastName: "Bello",
    phone: "08022334455",
    dob: "1992-11-03",
    gender: "Male",
    maritalStatus: "Single",
    address: "10 Akerele Street",
    town: "Surulere",
    state: "Lagos",
    nationality: "Nigerian",
    occupation: "Mechanic",
    employer: "Self-Employed",
    employerAddress: "10 Akerele Street, Surulere, Lagos",
  },
  {
    clientId: "CL004",
    accountnumber: "ACC004",

    email: "client4@example.com",
    firstName: "Ada",
    lastName: "Eze",
    phone: "08099887766",
    dob: "1996-07-18",
    gender: "Female",
    maritalStatus: "Single",
    address: "12 Ojuelegba Road",
    town: "Yaba",
    state: "Lagos",
    nationality: "Nigerian",
    occupation: "Retailer",
    employer: "Ada Ventures",
    employerAddress: "12 Ojuelegba Road, Lagos",
  },
  {
    clientId: "CL005",
    accountnumber: "ACC005",

    email: "client5@example.com",
    firstName: "Mustapha",
    lastName: "Sule",
    phone: "08123455667",
    dob: "1988-03-09",
    gender: "Male",
    maritalStatus: "Married",
    address: "3 Maitama Road",
    town: "Maitama",
    state: "Abuja",
    nationality: "Nigerian",
    occupation: "Civil Servant",
    employer: "Federal Ministry of Works",
    employerAddress: "Secretariat, Abuja",
  },
];

export default dummyClients;
